travis:
  secure:
    BINSTAR_TOKEN: VZjPjRwwAbjRqVG/6lT0rgivQ5SY/ZN1IbEXc/XIjtURNNLSajBemqm6wuCB8fj7IlpMX1CYw8gE/x0cDS1HiJPaxONdEI/y7HwjRVXVWKSP2HjpV5McMrL7yhfM6OOJzD51aDs0oNY7sg9o8FIaxaouAmwXVhridZ8zBo21E02g0TGb/LrKQysw0P+6ZNVlZipYBJt+aaiEh0Wqvr4ppMev2f/QZlkwxt3dNHEGna3LYDrfQRbDQIeFbv+PF36wFvx4X+j/y6wZCqbkpgQY6+zC/OqEcDAUMYeeTn+z6C7+Rl4YnmjDGn89Tvu763KS2I85iBNI6xYnIigXurOHqi5y3QW/LwmAP++gMkgdJqRmEV1hUpfVnlcpKj9ZerJ3I/DvzqlclBnafBqqx/CA9GLEab+4eNlKdqYQA9xce7E1m2/SbN1opGdf+oUKYTS9lwlGPyDUgeg3FQhulACOdx5ZqysI4r86MO3JjTmh48Ez9L8/PowPH0L2jQf7lkoP60QpMGGSzciVWLFRUXElbzwjv9ivtAaEAH4MujAS8S7U3mg7pe2cK5kwltK2UF/Y/w2oDB08D5zLobQQ5yOq5TmZeZS9R29D9PsOUt/obhic+cgJkSk9W6EDzbljJZHVvD26HU1X5DYADaoxXEccFIYywWoOrw9k+M7aUAPNS3g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
