travis:
  secure:
    BINSTAR_TOKEN: hgYpiUTMhIyX064LxC1xQ7R0pxCYroNKtqka1BDJrE1iuMBXlY2/LEtMXm7QGsPn32U0ZoQ5b02qMkCsTdkNo44VbBYbUwn6nd6+nNqL7jejlvE3Kc/dF+dMvygA4WRr3kXqDI7nErUQu8k+0lmLljaJkVOzo8fScQcZ72eeZPenjXSIqV+AJ3ZH7zvTLyydc46JSDuQcyMPxJMwPdLfc0qCpsuWJ1uZtTf7sbJctrcaxJIOcv163wSy+vXu5c9bw/Jgz5eTCySNCZFqRnACE28n6gSlOPYM8BTmvy+55ILB+Xp2a+lsLo12Bji7gw9m0zywYMwn5woOsR8HPie0conpsCAbZwc+UPwzh5Ot1/jDmx/CEJZk+2ZKfQ+vORhGIm4+d5K5yRJGV3SBFY66tyXYLQt0nqBjkimAxHgp4pRAgR+XKhFAQ1beN+h/IWrTs8y7f4i4sV6snJkgJHioHhdfEOEWxnzaxLYR6Rw8wtjb6QTNvjkKKdAmj35H6gKZAMiajNNoi5GXKcYq1QJc6xF0NoUKhzUpbhWfmKUZwgGg5yV3c5t9NS4htfyfuH8xVpGVaXBlaGpQFpaMDsU0sZcPAn8VbihHz/pIDi6hD/9PNz3iJKu6O/THj/m1FDeUAEr1Mqq09wppcPTYzxaOqTyAfbbqUL3P5fB92ml6+4U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
